### PR TITLE
Emit .d.ts to dist/ on build via "declaration" in tsconfig.json

### PR DESCRIPTION
**Pull request by danbeam**
This is so folks can consume this code in a more type safe way.

cc @catc @lencioni

### CODE REVIEW

**Review by lencioni — APPROVED** [review]

**Comment by skovhus** [comment]
I'm curious to understand the use case here. So I assume you have a project where you want to load the transformers from a TypeScript node-based setup and execute jscodeshift from your side?

**Comment by danbeam** [comment]
> I'm curious to understand the use case here. So I assume you have a project where you want to load the transformers from a TypeScript node-based setup and execute jscodeshift from your side?

We've built some codemods (in Typescript) that transform some internal testing infrastructure using some of the utils in jest-codemods. We initially added them directly to a fork of this project but it'd be much cleaner to use parts of jest-codemods as a library instead.

We upstreamed the Sinon codemod cuz that'd be helpful to others. But the rest wouldn't be (cuz the code they transform isn't publicly available).

**Comment by lencioni** [comment]
Correct me if I'm wrong @danbeam but I believe we are mostly (only?) using stuff from the helpers directory in this way. I see things like this:

```ts
import finale from 'jest-codemods/dist/utils/finale';
import { findParentOfType } from 'jest-codemods/dist/utils/recast-helpers';
import { modifyVariableDeclaration } from 'jest-codemods/dist/utils/sinon-helpers';
```

and this:

```ts
import { api } from 'jest-codemods/dist/utils/test-helpers';
```

**Comment by skovhus** [comment]
Thanks for the additional context. I always wondered if some of the utilities here should be shipped as a separate package. 

Especially the code mod CLI part that is now powering a lot of codemods (by copy pasting this and improving it). :)

**Pull request merged**
