### PR TITLE
Add the support for chai-should/expect

### PR DESCRIPTION
**Pull request by benjamin99**

### CODE REVIEW

**Comment by benjamin99** [comment]
Hi, 
just trying to add the transformers for chai (should & test) apis. Hope this PR can help the project.

**Comment by skovhus** [comment]
Hi! Thanks for doing this. 

There is already a fairly feature complete codemod for this, https://github.com/AlexJuarez/chai-to-jasmine/issues/1, that we have been talking about integrating (there is an issue for that). 

Did you have a look on that one? If not I think it makes sense to do that. Just copy paste the transformer and modify it to match our needs. 

Please ensure that you support all chai should methods, if something is not working there should be a warning. 

Again, thanks for taking your time doing this. : )

**Comment by benjamin99** [comment]
Sure I would be more than willing to do that. 
Would it be okey for you @AlexJuarez ?

**Comment by skovhus** [comment]
Seems so https://github.com/AlexJuarez/chai-to-jasmine/issues/1

**Comment by AlexJuarez** [comment]
If you could cleanup the chai-to-jamine transform @benjamin99 found here https://github.com/AlexJuarez/chai-to-jasmine/blob/master/transforms/chai-to-jasmine.js you could also copy in all of the tests https://github.com/AlexJuarez/chai-to-jasmine/tree/master/transforms/__testfixtures__/chai-to-jasmine.

Or if you want me to do that I could finish up my original PR. again I had stopped because the approaches are fairly different, and I wasn't sure how much @skovhus cared about conforming to the code style.

**Comment by skovhus** [comment]
As long as we have a good test coverage and it works, I really don't have hard feeling around style. Eslint --fix does most of the work. : )

**Comment by AlexJuarez** [comment]
@benjamin99 @skovhus I made a PR https://github.com/skovhus/jest-codemods/pull/43 see if that works for your needs. Thanks

**Comment by skovhus** [comment]
@benjamin99 thank you for your work here. I'll move the CLI work of this over to https://github.com/skovhus/jest-codemods/tree/AlexJuarez-chai-to-jasmine

Let me know if you would like to contribute to that branch. Maybe some of your tests cases can be moved over. 

Thanks!

**Pull request closed without merging**
