### PR TITLE
Transform assert.isFalse(foo) to expect(foo).toBe(false)

### LINKED ISSUE #20: assert.isFalse(foo) transformed to expect(foo).toBe()
I have `example.js` with the following:

```js
const assert = require('chai').assert;

const foo = false;
assert.isFalse(foo);
```

After running `jest-codemods example.js`, it looks like this:

```js
const foo = false;
expect(foo).toBe();
```

Where before no error would be thrown, after the change, Jest fails with this:

```
Error: expect(received).toBe(expected)

Expected value to be (using ===):
  undefined
Received:
  false
```

### PR DESCRIPTION
**Pull request by tschaub**
Fixes #20.

When `expectedOverride` is falsy, it is ignored.  So `assert.isFalse(foo)` currently gets transformed to `expect(foo).toBe()` (which asserts that `foo` is `undefined` instead of `false`).

An alternative to this change would be to properly handle falsy `expectedOverride` values.  But since `expectedOverride: 'NaN'` is used elsewhere, I followed suit.

I also updated the test cases so that `assert.isFalse()` and `assert.isNotFalse()` are called with [two arguments](http://chaijs.com/api/assert/#method_isfalse).

### CODE REVIEW

**Comment by skovhus** [comment]
I would rather check if expectedOverride is not undefined (as you propose). I'm not really sure why nan as a string works. Can you investigate?

**Comment by skovhus** [comment]
Any comments @paularmstrong

**Comment by skovhus** [comment]
So something like:
```
if (typeof expectedOverride !== 'undefined') {
```

**Comment by paularmstrong** [comment]
Yep :thumbsup:

**Comment by skovhus** [comment]
Wondering why making it a string (as in this PR) even works... `j.identifier('false')` should return the string `false`.

**Pull request closed without merging**
