### PR TITLE
Expect to jest transformer

### PR DESCRIPTION
**Pull request by skovhus**
@mjackson https://www.npmjs.com/package/expect is being integrated into Jest. This codemod automates the upgrade path. It is extending the work started in https://github.com/cpojer/js-codemod/pull/66

Background: https://github.com/facebook/jest/issues/1679

/cc @cpojer

Step 1
- [x] add initial codemod from https://github.com/cpojer/js-codemod/blob/master/transforms/expect.js by @vjeux 
- [x] `messages` from all matchers should be removed as some of them actually break Jest (e.g. `expect(object).toExist('remove me')`)
- [x] warning on usage of chained expect calls
- [x] remap non standard named expect import/require name
- [x] add more test cases
- [x] warn about comparator optional argument of `toInclude` and `toIncludeKeys` that is left but ignored by Jest
- [x] spyOn calls https://github.com/facebook/jest/issues/1679#issuecomment-282801070 and https://github.com/facebook/jest/issues/1679#issuecomment-282576745
 - - [x] andCall andReturn andThrow (createSpy and spyOn)
 - - [x] andCallThrough not supported in Jest?
 - - [x] `spy.calls[i].arguments[j] -> spy.mock.calls[i][j]`
 - - [x] `spy.calls.length -> spy.mock.calls.length`
 - - [x] `restoreSpies` and `resetSpies`
 - - [x] warn about `isSpy` is missing from Jest
 - - [x] `import expect, { createSpy, spyOn, isSpy } from 'expect'` warning
- [x] when running in standalone mode, running the transformer twice on the output shouldn't break or change anything (as `expect` will be used for both `expect@1` and the new Jest version, we cannot import detect).
- [x] toMatch can also be on objects, so cannot be translated 1:1 with Jest toMatch... See https://github.com/mjackson/expect#tomatch (maybe toMatchObject?) and https://github.com/ReactTraining/react-media/pull/61/files/886826394d672a721b7decaab3831d4af9d9177a#r124528600
- [x] expect allow expect argument to be undefined, Jest doesn't (example: `          expect(node.firstChild.innerHTML).not.toMatch(/hello/)` from `react-media`) 
- [x] ensure all matchers from `expect` are covered (or a warning is logged for unsupported features)

Step 2
- [x] try the codemod out on mjackson's or ReactTraining projects 
- - [x] react-router https://github.com/ReactTraining/react-router/pull/5027
- - [x] history https://github.com/ReactTraining/history/pull/468
- - [x] react-media https://github.com/ReactTraining/react-media/pull/61
- - [x] fix failures due to https://github.com/facebook/jest/issues/3360
- [x] consider if other transformers in jest-codemods would benefit form the standalone mode option (being able to run in node)
- [x] document standalone mode 
- [x] document steps to do after codemod has run
- [x] figure out if package is called `expect` or `jest-matchers`

### Bugs
- [x] `console.error` does't have `calls` property when using `jest` spies:
```
  it('warns when passed a history prop', () => {
    const history = {}
    const node = document.createElement('div')
    expect.spyOn(console, 'error')

    ReactDOM.render((
      <MemoryRouter history={history} />
    ), node)

    expect(console.error.calls.length).toBe(1)
    expect(console.error.calls[0].arguments[0]).toMatch(
      /<MemoryRouter.*import \{ Router }/)
    expect.restoreSpies()
  })
```

### CODE REVIEW

**Comment by mjackson** [comment]
Thank you, @skovhus :) How can I try this out? I'm not familiar with how to run a code mod. Is there a doc somewhere?

**Comment by skovhus** [comment]
Hi @mjackson. 

I'll update you when the codemod is ready. But this repo has a little CLI that should make it fairly easy to run on an existing codebase. It wraps jscodeshift. 

But I might try the codemod out on some of your repos with expect. ; )

**Comment by skovhus** [comment]
@mjackson for projects like React History and React Router it seems that you are using Expect+Karma+Mocha to execute your tests in Chrome or other browsers.

As Jest is executed in node only, these projects might not be good candidates for testing this codemod. Unless if you are interested in switching to a node only test environment? Let me know what you think : )

**Comment by cpojer** [comment]
This is fantastic.

@skovhus The new version of `expect` must definitely also be made to work on the web. So this codemod should enable people to switch from the previous version of expect to the new version. One way to try that out would be to run the codemod on react history/react router and then add `jest-matchers` and change `const expect = require('jest-matchers')` and make sure that works in the browser.

We may have to provide a single-file build for jest-matchers, that's still to be decided.

The idea is to ship this breaking change sometime in mid April.

**Comment by skovhus** [comment]
Thanks for the input! So essentially two uses cases: for upgrading expect and for upgrading to use Jest as test runner. 

The output of these two cases can be made compatible if we leave the jest-matchers input in there. 

So if we import expect from jest-matchers even for users just running on node... that might make sense, as we don't need two codemods or configuration.

**Comment by cpojer** [comment]
Hmm, here would be my recommendation:

* Transform with Jest:
 * `expect.spyOn` => `jest.spyOn`, `expect.spy` => `jest.fn`
 * `require('expect')` gets removed.
* Transform without Jest:
 * `expect.spyOn` => `mock.spyOn`, `expect.spy` => `mock.fn` by including `jest-mock`.

The module `jest-matches` will be renamed to `expect`, so the require statement does not need to changed. Inside of Jest, we don't need to require it because it is globally available.

**Comment by skovhus** [comment]
Two codemods (or configuration) it is. 👍🏻

**Comment by cpojer** [comment]
btw. this plugin should help insert requires for the second one: https://github.com/cpojer/js-codemod/tree/master/extensions/imports

**Comment by brantphoto** [comment]
hi @skovhus I'm excited to use this codemod. We'll be using this exact scenario to move to Jest at my work. Thanks for making it!

**Comment by skovhus** [comment]
@brantphoto so happy to hear that! : )

I'll let you know when you can try it out. 👍

**Comment by skovhus** [comment]
Blocked on https://github.com/facebook/jest/issues/3360

**Comment by cpojer** [comment]
Hey Kenneth! What's the status of this PR? Are you going to merge it? Except for the blocker inside of Jest, is there anything else left that we need to do?

**Comment by skovhus** [comment]
Nope. Planning to merge it when the standalone mode works for React Router. 

Everything else should be fine. 😀

**Comment by skovhus** [comment]
@cpojer is the plan still to rename `jest-matchers` to `expect` (and release as version 2)? 

Do we want to do that before this codemod goes out? Or should we just change this codemod to migrating from `expect@1` to `jest-matchers`?

**Comment by cpojer** [comment]
We'll publish expect@20 or @21, yes. I'm not sure when yet, but that's the plan.

**Pull request merged**
