### PR TITLE
jasmine globals

### PR DESCRIPTION
**Pull request by aaronabramov**
we're migrating from using `jasmine` to using `jest-circus` and i'm writing some codemods that'll simplify the migration.
this is not going to be perfect, because there's a lot of state that's impossible to track through AST, but hopefully it can get us closer to the full migration

### CODE REVIEW

**Comment by SimenB** [comment]
I don't know how you wanna go, but e.g. `expect(mock.calls.count()).toHaveLength(1)` or `expect(mock.calls.count().length).toBe(1)` can both be converted to `expect(mock).toHaveBeenCalledTimes(1)`. That last one is compatible with both Jest spies and jasmine spies, so then it doesn't matter if the spy was created by a `jasmine.createSpy` or `jest.fn`

**Comment by skovhus** [comment]
@aaronabramov let me know if you want to add the CLI support and documentation, else I'll do it. :)

Pointers to where we need to change stuff:
- https://github.com/skovhus/jest-codemods/blob/master/src/cli/index.js#L50
- we don't want this converter in https://github.com/skovhus/jest-codemods/blob/master/src/cli/index.js#L55 (as we don't have input detection)
- https://github.com/skovhus/jest-codemods/blob/master/src/cli/index.js#L87

**Comment by aaronabramov** [comment]
added to CLI, just two lines, right?
there's no mention of `jasmine` in `README.md` so i didn't touch it :)

**Comment by aaronabramov** [comment]
@SimenB i don't think this codemod will cover a lot of cases honestly. my goal is to just make it not crash on `jasmine is undefined` :P most of the use cases i found so far are way more complicated.. like
`stuff.calls.mostRecent().args()` which needs to be replaced with `stuff.mock.calls[stuff.mock.calls.length - 1][0]`
so yeah.. it's pretty complex :)

**Comment by aaronabramov** [comment]
added `jasmine.createSpy()` -> `jest.fn()` transform as well

**Comment by aaronabramov** [comment]
been migrating a lot of tests this week. added some more globals + better spyOn support

**Comment by skovhus** [comment]
Thanks! 🙌

**Comment by skovhus** [comment]
Released as `jest-codemods@0.15`. 🚀

**Pull request merged**
